SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

CREATE DATABASE IF NOT EXISTS `wordpress_local` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `wordpress_local`;
